// <auto-generated />
using System;
using Avocado.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avocado.Server.Data.Migrations
{
    [DbContext(typeof(AvocadoDbContext))]
    [Migration("20260807071431_BackfillDocumentTimestamps")]
    partial class BackfillDocumentTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Avocado.Server.Features.Activities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tracking_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserId");

                    b.HasIndex("MatterId", "OccurredAt");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Billings.BillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountExclVatCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_excl_vat_cents");

                    b.Property<long>("BilledTimeCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("billed_time_cents");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_reference");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_paid");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_on");

                    b.HasKey("Id");

                    b.HasIndex("IsPaid");

                    b.HasIndex("MatterId", "Date");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Billings.BillingLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.HasKey("Id");

                    b.HasIndex("MatterId", "Date");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("AttachedAs")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("attached_as");

                    b.Property<Guid?>("AttachedToContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("attached_to_contact_id");

                    b.Property<string>("Civility")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("civility");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("LegalForm")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_form");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Siren")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("siren");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AttachedToContactId");

                    b.HasIndex("LastName");

                    b.HasIndex("LegalName");

                    b.HasIndex("Siren");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Deadlines.Deadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_done");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<int>("RemindDaysBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remind_days_before");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IsDone", "Date");

                    b.HasIndex("MatterId", "IsDone", "Date");

                    b.ToTable("deadlines", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_id");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("BlobSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("blob_sha256");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_date");

                    b.Property<string>("ExhibitLabel")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("exhibit_label");

                    b.Property<int?>("ExhibitNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exhibit_number");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Type")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("BlobSha256");

                    b.HasIndex("MatterId");

                    b.HasIndex("MatterId", "ExhibitNumber")
                        .IsUnique()
                        .HasFilter("exhibit_number IS NOT NULL");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Matters.Matter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT")
                        .HasColumnName("classification");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_on");

                    b.Property<string>("Court")
                        .HasColumnType("TEXT")
                        .HasColumnName("court");

                    b.Property<string>("CourtCaseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("court_case_number");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("HourlyRateCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hourly_rate_cents");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_favourite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_on");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClosedOn");

                    b.HasIndex("CourtCaseNumber");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("matters", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Matters.MatterParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<bool>("IsClient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_client");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("MatterId", "ContactId")
                        .IsUnique();

                    b.ToTable("matter_parties", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Settings.PracticeSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("practice_settings", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Templates.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BlobSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("blob_sha256");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.TimeEntries.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_minutes");

                    b.Property<long?>("HourlyRateCentsOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hourly_rate_cents_override");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_billable");

                    b.Property<Guid>("MatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("matter_id");

                    b.Property<TimeOnly?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("task");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Date");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UserId");

                    b.HasIndex("MatterId", "Date");

                    b.ToTable("time_entries", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<long>("HourlyRateCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hourly_rate_cents");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Avocado.Server.Features.Activities.Activity", b =>
                {
                    b.HasOne("Avocado.Server.Features.Contacts.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avocado.Server.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("Matter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avocado.Server.Features.Billings.BillingInvoice", b =>
                {
                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("Avocado.Server.Features.Billings.BillingLedgerEntry", b =>
                {
                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("Avocado.Server.Features.Contacts.Contact", b =>
                {
                    b.HasOne("Avocado.Server.Features.Contacts.Contact", "AttachedTo")
                        .WithMany()
                        .HasForeignKey("AttachedToContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttachedTo");
                });

            modelBuilder.Entity("Avocado.Server.Features.Deadlines.Deadline", b =>
                {
                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("Avocado.Server.Features.Documents.Document", b =>
                {
                    b.HasOne("Avocado.Server.Features.Activities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("Avocado.Server.Features.Matters.MatterParty", b =>
                {
                    b.HasOne("Avocado.Server.Features.Contacts.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany("Parties")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("Avocado.Server.Features.TimeEntries.TimeEntry", b =>
                {
                    b.HasOne("Avocado.Server.Features.Activities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avocado.Server.Features.Billings.BillingInvoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avocado.Server.Features.Matters.Matter", "Matter")
                        .WithMany()
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avocado.Server.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("Invoice");

                    b.Navigation("Matter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avocado.Server.Features.Matters.Matter", b =>
                {
                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
