/** Injected by the preload. The only things the renderer receives from the main process. */
declare global {
  interface Window {
    avocado: {
      connection: () => Promise<{ url: string; token: string; vaultState: string }>
      chooseFolder: (startIn?: string) => Promise<string | null>
      removableDrives: () => Promise<{ path: string; label: string; freeBytes: number }[]>
      saveRecoveryKey: (drivePath: string, contents: string) => Promise<string>
      exportRecoverySheet: () => Promise<string | null>
      openWorkingCopy: (path: string) => Promise<string | null>
      saveAs: (fileName: string, base64: string) => Promise<string | null>
    }
  }
}

export type VaultState = 'Absent' | 'Locked' | 'Unlocked'

export interface VaultStatus {
  state: VaultState
  directory: string
  lockReason: string | null
  vaultId: string | null
  hasRecoveryKey: boolean
  suggestedDirectory: string
}

/** Keys generated in memory. Nothing has been written to disk yet. */
export interface VaultPrepared {
  /** Shown once. Never fetched again, never stored. */
  recoveryCode: string
}

export interface VaultCreated {
  vaultId: string
  directory: string
}

/**
 * Thrown for a non-2xx response, carrying the backend's own French message where it sent one.
 * The API answers with ProblemDetails, so `detail` and validation errors are worth surfacing —
 * « Ce dossier est inclus dans un dossier synchronisé » beats « Erreur 400 ».
 */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    /** Stable identifier from the backend, e.g. `synced-folder`. Branch on this, never on the text. */
    readonly code?: string,
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

interface ProblemDetails {
  title?: string
  detail?: string
  code?: string
  errors?: Record<string, string[]>
}

let connection: { url: string; token: string } | null = null

async function connect(): Promise<{ url: string; token: string }> {
  connection ??= await window.avocado.connection()
  return connection
}

/**
 * Every call carries this launch's bearer token. Without it the backend answers 401 — which is what
 * stops another local process, or a page open in a browser, from reading the vault over loopback.
 *
 * While the vault is shut, everything except `/api/vault` and `/health` answers 503; the renderer
 * reads the state from `/api/vault/status` rather than inferring it from a failure.
 */
export async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const { url, token } = await connect()

  const response = await fetch(`${url}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      // Only for JSON. FormData must set its own header so the browser can add the multipart
      // boundary; forcing application/json on an upload is what produced a 415.
      ...(typeof init.body === 'string' ? { 'Content-Type': 'application/json' } : {}),
      ...init.headers,
    },
  })

  if (!response.ok) {
    const problem = await read(response)
    throw new ApiError(response.status, describe(problem, response.status), problem.code)
  }

  return response.status === 204 ? (undefined as T) : ((await response.json()) as T)
}

export const post = <T>(path: string, body: unknown): Promise<T> =>
  api<T>(path, { method: 'POST', body: JSON.stringify(body) })

/**
 * Opening a document has to go through the same bearer token as everything else, so the file is
 * fetched and handed to the browser as a blob rather than pointed at with an href. A plain link would
 * reach the backend without the header and collect a 401.
 */
export async function download(path: string, fileName: string): Promise<void> {
  const { url, token } = await connect()
  const response = await fetch(`${url}${path}`, { headers: { Authorization: `Bearer ${token}` } })

  if (!response.ok) {
    const problem = await read(response)
    throw new ApiError(response.status, describe(problem, response.status), problem.code)
  }

  const href = URL.createObjectURL(await response.blob())
  const link = document.createElement('a')

  link.href = href
  link.download = fileName
  link.click()

  URL.revokeObjectURL(href)
}

/**
 * Fetches generated bytes and asks the shell where to put them. Used for the billing annexe, where a
 * blob download would land in the browser's download folder rather than somewhere she chose.
 */
export async function saveAs(path: string, fileName: string): Promise<string | null> {
  const { url, token } = await connect()
  const response = await fetch(`${url}${path}`, { headers: { Authorization: `Bearer ${token}` } })

  if (!response.ok) {
    const problem = await read(response)
    throw new ApiError(response.status, describe(problem, response.status), problem.code)
  }

  const bytes = new Uint8Array(await response.arrayBuffer())
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)

  return window.avocado.saveAs(fileName, btoa(binary))
}

/** Multipart upload without the JSON content type, which is what a FormData body needs. */
export const upload = <T>(path: string, form: FormData): Promise<T> =>
  api<T>(path, { method: 'POST', body: form })

async function read(response: Response): Promise<ProblemDetails> {
  try {
    return (await response.json()) as ProblemDetails
  } catch {
    return {}
  }
}

function describe(problem: ProblemDetails, status: number): string {
  const validation = Object.values(problem.errors ?? {}).flat()

  return validation[0] ?? problem.detail ?? problem.title ?? `Erreur ${status}`
}
